DROP TABLE IF EXISTS EVENT;

CREATE TABLE EVENT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  project_name VARCHAR(250) NOT NULL,
  project_date VARCHAR(19) NOT NULL,
  project_description VARCHAR(250) DEFAULT NULL
);